[package]
name = "epigrammars"
version = "0.1.0"
edition = "2024"

[dependencies]
bnf = "0.5.0"
leptos = { version = "0.8.5", features = ["csr"] }
stylance = "0.7.0"

[package.metadata.stylance]
output_file = "./bundle.scss"

