name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    
    - uses: cargo-bins/cargo-binstall@main
    
    - name: Install Trunk and Stylance (fast via binstall)
      run: cargo binstall trunk stylance-cli --no-confirm

    - name: Rebuild styles
      run: stylance .

    - name: Rebuild app
      run: trunk build --verbose

    - name: Check output
      run: ls -la dist

